import { sample } from 'lodash';
import { faker } from '@faker-js/faker';

// ----------------------------------------------------------------------

export const users = [
  {
    id: '1',
    avatarUrl: '/assets/images/avatars/avatar_1.jpg',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@example.com',
    phone: '9876543210',
    address: '123, MG Road, Delhi',
    relation: 'Father',
    dob: new Date('1975-05-20'),
    occupation: 'Engineer',
    degree: 'B.Tech',
    institution: 'IIT Delhi',
    year: '2015',
    grade: 'A',
    jobTitle: 'Software Engineer',
    company: 'Tata Consultancy Services',
    experience: '5 years',
    location: 'Bangalore',
    docType: 'Aadhar Card',
    docNumber: '123456789012',
    issueDate: new Date('2010-01-01'),
    expiryDate: new Date('2030-01-01'),
    condition: 'Diabetes',
    doctor: 'Dr. Mehta',
    medication: 'Metformin',
    notes: 'Needs regular check-ups',
    benefit: 'Scholarship',
    amount: '₹5000',
    date: new Date('2021-06-15'),
    reason: 'Merit',
    isVerified: true,
    status: 'active',
    role: 'Leader',
  },
  {
    id: '2',
    avatarUrl: '/assets/images/avatars/avatar_2.jpg',
    name: 'Priya Kapoor',
    email: 'priya.kapoor@example.com',
    phone: '9876543211',
    address: '456, Park Street, Mumbai',
    relation: 'Mother',
    dob: new Date('1980-11-10'),
    occupation: 'Doctor',
    degree: 'MBBS',
    institution: 'AIIMS',
    year: '2010',
    grade: 'A',
    jobTitle: 'HR Manager',
    company: 'Infosys',
    experience: '10 years',
    location: 'Hyderabad',
    docType: 'PAN Card',
    docNumber: 'ABCDE1234F',
    issueDate: new Date('2012-05-20'),
    expiryDate: new Date('2025-05-20'),
    condition: 'Hypertension',
    doctor: 'Dr. Gupta',
    medication: 'Lisinopril',
    notes: 'Regular medication required',
    benefit: 'Subsidy',
    amount: '₹7000',
    date: new Date('2021-03-10'),
    reason: 'Financial Need',
    isVerified: false,
    status: 'active',
    role: 'HR Manager',
  },
  // Add three more users similarly
  {
    id: '3',
    avatarUrl: '/assets/images/avatars/avatar_3.jpg',
    name: 'Amit Verma',
    email: 'amit.verma@example.com',
    phone: '9876543212',
    address: '789, Residency Road, Bangalore',
    relation: 'Brother',
    dob: new Date('1990-07-14'),
    occupation: 'Business',
    degree: 'MBA',
    institution: 'IIM Bangalore',
    year: '2018',
    grade: 'B',
    jobTitle: 'Project Manager',
    company: 'Wipro',
    experience: '3 years',
    location: 'Chennai',
    docType: 'Passport',
    docNumber: 'M1234567',
    issueDate: new Date('2015-09-01'),
    expiryDate: new Date('2025-09-01'),
    condition: 'Asthma',
    doctor: 'Dr. Reddy',
    medication: 'Albuterol',
    notes: 'Carry inhaler at all times',
    benefit: 'Grant',
    amount: '₹6000',
    date: new Date('2021-09-20'),
    reason: 'Health',
    isVerified: true,
    status: 'active',
    role: 'Project Manager',
  },
  {
    id: '4',
    avatarUrl: '/assets/images/avatars/avatar_4.jpg',
    name: 'Sanjay Singh',
    email: 'sanjay.singh@example.com',
    phone: '9876543213',
    address: '101, Brigade Road, Hyderabad',
    relation: 'Sister',
    dob: new Date('1985-02-18'),
    occupation: 'Teacher',
    degree: 'B.Sc',
    institution: 'NIT Trichy',
    year: '2017',
    grade: 'A',
    jobTitle: 'Backend Developer',
    company: 'HCL Technologies',
    experience: '4 years',
    location: 'Pune',
    docType: 'Driving License',
    docNumber: 'DL12345678',
    issueDate: new Date('2014-12-15'),
    expiryDate: new Date('2024-12-15'),
    condition: 'None',
    doctor: 'Dr. Sharma',
    medication: 'None',
    notes: 'No known conditions',
    benefit: 'Scholarship',
    amount: '₹8000',
    date: new Date('2021-12-05'),
    reason: 'Merit',
    isVerified: false,
    status: 'banned',
    role: 'Backend Developer',
  },
  {
    id: '5',
    avatarUrl: '/assets/images/avatars/avatar_5.jpg',
    name: 'Neha Gupta',
    email: 'neha.gupta@example.com',
    phone: '9876543214',
    address: '202, Church Street, Chennai',
    relation: 'Spouse',
    dob: new Date('1988-09-25'),
    occupation: 'Engineer',
    degree: 'M.Tech',
    institution: 'BITS Pilani',
    year: '2016',
    grade: 'A',
    jobTitle: 'Full Stack Developer',
    company: 'Tech Mahindra',
    experience: '6 years',
    location: 'Delhi',
    docType: 'Aadhar Card',
    docNumber: '987654321098',
    issueDate: new Date('2009-08-01'),
    expiryDate: new Date('2029-08-01'),
    condition: 'None',
    doctor: 'Dr. Kumar',
    medication: 'None',
    notes: 'No known conditions',
    benefit: 'Grant',
    amount: '₹9000',
    date: new Date('2022-01-25'),
    reason: 'Financial Need',
    isVerified: true,
    status: 'active',
    role: 'Full Stack Developer',
  },
];
